version: "3.2"
services:
  app:
    build: .
    image: chamber:1
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
  postgres:
    image: postgres:10-alpine
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: chamber
      POSTGRES_PASSWORD: postgres